# -*- coding: utf-8 -*-
"""Copy of Copy of delete_word.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_H7ShJtKt6Kf76OMan0YkT7Xa_6zeBB7
"""

!pip install gradio
!pip install google.cloud.speech
!pip install wavio

import os
import google.cloud.speech as g
import gradio as gr
import wave
from os.path import exists, join, basename, splitext
import sys
import librosa
import wavio
import regex as re
import pandas as pd
import ipywidgets as widgets
import numpy as np
from pydub import AudioSegment
from scipy.io import wavfile
from moviepy.video.io.ffmpeg_tools import ffmpeg_extract_subclip

from google.colab import drive
drive._mount('/content/drive')

os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = r'/content/drive/MyDrive/help.json'

def delete_word(audio, word,occurence):
  df1=print_occurences(audio,word)
  start_time = float(df1['start_offset'][occurence])
  end_time = float(df1['end_offset'][occurence])
  end=librosa.get_duration(filename=audio.name)
  clip_1 = ffmpeg_extract_subclip(audio.name, 0, start_time, targetname = r"clip_1.wav")
  clip_2 = ffmpeg_extract_subclip(audio.name, end_time, end, targetname = r"clip_2.wav")
  sound1 = AudioSegment.from_wav(r"clip_1.wav")
  sound2 = AudioSegment.from_wav(r"clip_2.wav")
  final = sound1+sound2
  final.export(r"final.wav", format="wav")
  
  sr, audio = wavfile.read('final.wav')
  return sr,audio

delete_word("/content/drive/MyDrive/Colab Notebooks/test.wav", "Start",0)

iface = gr.Interface(fn=delete_word, inputs=["file","text","number"], outputs="audio",examples=[["/content/drive/MyDrive/test.wav",'with','0']], title='Delete word', description="To delete a word, upload the audio in the wav format and enter the word to be deleted and the occurence you want to delete. All occurences of the word can be found by going on the find occurence page").launch(share=True)

