# -*- coding: utf-8 -*-
"""Copy of Copy of print_occurences.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UCNBs3RfRUryYFV_XMWZQ6jhTnCKMo7o
"""

!pip install gradio
!pip install google.cloud.speech
!pip install wavio

import os
import google.cloud.speech as g
import gradio as gr
import wave
from os.path import exists, join, basename, splitext
import sys
import librosa
import wavio
import regex as re
import pandas as pd
import ipywidgets as widgets
import numpy as np
from pydub import AudioSegment
from scipy.io import wavfile
from moviepy.video.io.ffmpeg_tools import ffmpeg_extract_subclip

from google.colab import drive
drive._mount('/content/drive')

os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = r'/content/drive/MyDrive/help.json'

def create_dataframe(audio):
  generate_transcripts(audio)
  df = pd.read_csv(r'/content/timeoffset.csv', header = None, error_bad_lines=False)
  df.rename(columns = {0 : 'Word', 1 : 'start_offset', 2 : 'end_offset'}, inplace = True)
  return df

def print_occurences(audio,word):
  df = create_dataframe(audio)
  df1 = pd.DataFrame(columns=['Word','start_offset','end_offset'])
  for i in range(df.shape[0]):
      if word==df['Word'][i]:
          df1.loc[len(df1.index)] = [df['Word'][i], df['start_offset'][i],  df['end_offset'][i]] 
  return df1

print_occurences("/content/drive/MyDrive/Colab Notebooks/test.wav","to")

iface = gr.Interface(fn=print_occurences, inputs=["file","text"], outputs="text",examples=[["/content/drive/MyDrive/test.wav","to"]], title='Print Occurences', description="To get all occurences of a word, upload the audio file in wav format and enter the word whose occurences are needed").launch(share=True)

