# -*- coding: utf-8 -*-
"""Transcripts.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hsGfUY7SKqxfShPx3rLx9Xcn2sNPP2Bj
"""

!pip install protobuf==3.17.3
!pip install gradio
!pip install google.cloud.speech 
!pip install wavio

import os
import google.cloud.speech as g
import gradio as gr
import wave
from os.path import exists, join, basename, splitext
import sys
import librosa
import wavio
import regex as re
import pandas as pd
import ipywidgets as widgets
import numpy as np
from pydub import AudioSegment
from scipy.io import wavfile
from moviepy.video.io.ffmpeg_tools import ffmpeg_extract_subclip

from google.colab import drive
drive.mount('/content/drive')

os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = r'/content/instant-guard-329502-fe22bb7c1e5a.json'

def generate_transcripts(audio):
#     return type(audio)
#     return audio.name
    client = g.SpeechClient()
    with open(audio.name, 'rb') as f1:
        byte_data_wav = f1.read()
# #     rate, data = audio
    f1 = wave.open(audio.name, "r")
    
# #     num_channels_file1 = data.shape[1]
    num_channels_file1 = int(f1.getnchannels())
    
    audio_wav = g.RecognitionAudio(content = byte_data_wav)
#     return "abc"
    config = g.RecognitionConfig(
    enable_automatic_punctuation = True,
    language_code = 'en-US', 
    audio_channel_count= num_channels_file1,
    enable_separate_recognition_per_channel=False,
    enable_word_time_offsets=True,
    )
    operation = client.long_running_recognize(config = config, audio = audio_wav)

    result = operation.result(timeout=90)
      
    with open("transcript.txt",'w') as f:
        pass
    s = ""
    with open("transcript.txt", 'a+') as f:
        
        for result in result.results:
            alternative = result.alternatives[0]
            para = alternative.transcript
            print(para, file = f)
            s += para

    result = operation.result(timeout=90)
    with open("timeoffset.csv",'w') as f:
        pass
    with open("timeoffset.csv", 'a+') as f:
            for result in result.results:
                alternative = result.alternatives[0]
                for word_info in alternative.words:
                    word = word_info.word
                    start_time = word_info.start_time
                    end_time = word_info.end_time
                    x = f"Word: {word}, start_time: {start_time.total_seconds()}, end_time: {end_time.total_seconds()}"
                    y = f"{word}, {start_time.total_seconds()}, {end_time.total_seconds()}"
                    print(y, end='\n', file=f)

    return s

iface = gr.Interface(fn=generate_transcripts, inputs= "file", outputs="text",examples=[['/content/drive/MyDrive/test.wav']], title='Get transcripts', description='To obtain transcripts of your audio file, upload your audio file in wav format and click the submit button.').launch(share=True)